Design Guide
============
:toc:

== General Design

Ultimately the idea here is to redefine how Hibernate generates and executes SQL .  Part of this is the 
SQM parser for handling semantic interpretation of HQL, JPQL and criteria queries.  Part is building 
an "SQL AST" from various sources:

* SQM and options
* get & load handling (single and multi id) 
* persister-driven DML handling (save, persist, merge, etc)

Building SQM is defined by the hibernate-semantic-query project.

question - does SQM incorporate entity-graphs?  seems better to have the thing that interprets SQM to apply
entity-graphs.

question - better for persister to incorporate the model descriptor?  Or for persister to simply hold 
reference to model descriptor?  The latter seems best (certainly least disruptive), however that makes querying
MappedSuperclasses more difficult.  This really comes down to a decision of whether to model MappedSuperclass
in the EntityPersister hierarchy.  As a follow-on to this... we should incorporate a representation of
MappedSuperclass into the SQM domain model.  Seems that the spec does not allow querying MappedSuperclasses; verify!


== Tables and Groups and Spaces (oh my)

Modeling the from-clause is central to SQM and its translation.  In translating SQM into an SQL AST 
we build the following types:

TableSpecification:: Models an singular table reference.  This could be either a real table reference 
(PhysicalTableSpecification) or an inline-view (DerivedTableSpecification).

TableSpecificationGroup:: Represents a related group of TableSpecification instances.  Specifically it models
the TableSpecification originating from a given entity/collection persister (see the "improved" persister contracts).

TableSpecificationGroupJoin:: Represents a TableSpecificationGroup along with the type of join and any predicate.
used to represent joins between "persister references".

TableSpace:: Models what ANSI SQL calls a "table reference".  Easiest way to think of this is the comma separated groups
of "from elements".

FromClause:: groups one or more TableSpaces.

Let's look at some examples to make this more clear...

[source]
.select e from Entity e (basic)
----
FromClause
    TableSpace
        root=TableSpecificationGroup(com.acme.Entity, "e")
            root=PhysicalTableSpecification("t_entity", "e0")
            joins={}
        joins={}
----
  
[source]
.select e from Entity e (secondary table)
----
FromClause
    TableSpace
        root=TableSpecificationGroup(com.acme.Entity, "e")
            root=PhysicalTableSpecification("t_entity", "e0")
            joins={
                TableSpecificationJoin
                    PhysicalTableSpecification("t_entity_secondary", "e1")
                    INNER
                    <join predicate>
            }
        joins={}
----
  
[source]
.select e from Entity e (joined inheritance)
----
FromClause
    TableSpace
        root=TableSpecificationGroup(com.acme.Entity, "e")
            root=PhysicalTableSpecification("t_entity", "e0")
            joins={
                TableSpecificationJoin
                    PhysicalTableSpecification("t_entity_secondary", "e1")
                    INNER
                    <join predicate>
            }
        joins={}
----

[source]
.select e from Entity e, SecondEntity se
----
FromClause
    TableSpace
        root=TableSpecificationGroup(com.acme.Entity, "e")
            root=PhysicalTableSpecification("t_entity", "e0")
            joins={}
        joins={}
    TableSpace
        root=TableSpecificationGroup(com.acme.SecondEntity, "se")
            root=PhysicalTableSpecification("t_second_entity", "se0")
            joins={}
        joins={}
----

[source]
.select e from Entity e inner join SecondEntity se on ...
----
FromClause
    TableSpace
        root=TableSpecificationGroup(com.acme.Entity, "e")
            root=PhysicalTableSpecification("t_entity", "e0")
            joins={}
        joins={
            TableSpecificationGroupJoin
                EntityTableSpecificationGroup
                    TableSpecificationGroup(com.acme.SecondEntity, "se")
                    INNER
                    <join predicate>
        }
----




== Parameters

There are multiple "parts" to parameter handling...

=== ParameterSpec

A ParameterSpec is the specification of a query parameter (name/position, type, etc).  It represents the
expectation(s) after parsing a query string.

Consider:

[source]
----
Query q = session.createQuery( "select p from Person p where p.name = :name" );
----

At this point the (Named)ParameterSpec for `":name"` has been parsed.   ParameterSpec needs to understand
anticipatedType.  Here, because `Person#name` is a `StringType` we would anticipate `":name"` to also 
be a `StringType`; we will see later that ParameterBinding can adjust that.  

It may also be a good idea to allow for a ParameterSpec to specify a requiredType.  This would accomodate
cases where the placement of the parameter in the query requires a certain Type to used.

Proposed ParameterSpec contract:

[source]
----
interface ParameterSpec {
    String getName();
    Integer getPosition();
    Type getAnticipatedType();
    Type getRequiredType();
}
----


=== ParameterBinding

ParameterBinding is the binding for a parameter.  Defined another way, it represents the value 
specified by the user for the parameter for this execution of the query.  

It can be thought of as the combination of a ParameterSpec, the specified value as well as some 
additional specifics like Type, TemporalType handling, etc.

This part comes from the user.  Consider:

[source]
----
Query q = session.createQuery( "from Person p where p.name = :name" );
query.setParameter( "name", "Billy" );
----

Here, the `#setParameter` call creates the ParameterBinding.  This form would
"pick up" the anticipated-Type from the ParameterSpec.  We'd also allow 
specifying the Type to use.

I think we should limit the overloaded form of this.  I can see the following options (using
named parameters for illustration):

[source]
----
interface Query {
    ...

    ParameterSpec getParameterSpec(String name);
    
    // returning this to keep API as before...

    Query setParameter(String name, Object value);
    Query setParameter(String name, Object value, Type type);
    Query setParameter(String name, Date value, TemporalType temporalType);
    Query setParameter(String name, Calendar value, TemporalType temporalType);
}
----


Proposed ParameterBinding contract:

[source]
----
interface ParameterBinding {
    ParameterSpec getParameterSpec();

    Object getValue();

    Type getType();
    TemporalType getTemporalType();
}
----


=== ParameterBinder

This is more of an esoteric concept at this point, but ultimately the idea is the binding of the 
parameter value to JDBC.  It would be best to drive the binding of parameter values from "nodes 
embedded in the query AST".  This could be a case where the implementation of ParameterSpec 
additionally implements this "binding contract" as well.


